### ISSUE TITLE
OBS 2.10 generates SHA-1 signatures for dpkg files by default, not accepted by Debian >= 9

### ISSUE THREAD

**Issue by laf0rge** [openSUSE/obs-sign#25]
I just did a fresh/clean install of the OBS 2.10 appliance installer, and I was unable to use apt-get with the generated packages due to SHA-1 being phased out by Debian 9 in 2016, while obs-sign still generates SHA-1 signatures by default.

Yes, one can tweak /etc/sign.conf.  But it's 2020, and all major dpkg based distributions have for many years rejected SHA-1 signatures.  So I would argue the default should be SHA-256 for quite some time.

This avoids anyone else having to invest many hours of his life trying to figure out why on earth the OBS-built packages will not work despite having installed Release.key with apt-key, etc.

**Comment by laf0rge** [comment]
See also the thread at http://opensuse.14.x6.nabble.com/OBS-does-NOT-support-sha256-hashes-on-the-default-GPG-key-td5093297.html#a5093307 where this problem was pointed out already in 2017

**Comment by laf0rge** [comment]
see also #5

**Comment by mlschroe** [comment]
I wish it would be so easy. The problem is that we must not use sha256 for DSA keys, as the nss glue code in rpm does not deal correctly with DSA2 signatures.

What I did instead was change the OBS code in the publisher so that it also switches to sha256 if the default sign key is used and is of type RSA. See https://github.com/openSUSE/open-build-service/pull/10375
