### ISSUE TITLE
Support different hash algorithms than SHA1 which triggers a warning in Apt 1.2.6+

### ISSUE THREAD

**Issue by jktjkt** [openSUSE/obs-sign#5]
Anything in OBS currently triggers an apt warning due to a weak signature algorithm:

<pre># apt-get update
# W: http://download.opensuse.org/repositories/home:/jkt-gentoo:/trojita/Debian_8.0/Release.gpg:
Signature by key 62797E5BC0F3A65DCFB2F94D121EE1B7A6A36662 uses weak
digest algorithm (SHA1)</pre>

https://wiki.debian.org/Teams/Apt/Sha1Removal

Note that that page says that it might be necessary to switch from DSA to RSA keys, too. However, only asking OBS to re-generate the key is not sufficient to fix this problem.

**Comment by jnweiger** [comment]
@mlschroe https://github.com/owncloud/core/issues/23599 has a patch. to add '--hash sha256' in one place where obs-sign is called. Could you please review?

**Comment by jnweiger** [comment]
Ping. @hennevogel @adrianschroeter can you please check, if this is already deployed?

We are getting reports it still is not.
https://github.com/owncloud/client/issues/4596

**Comment by adrianschroeter** [comment]
We do sign with SHA1 _and_ SHA256 since quite some time. Does that mean that apt complains about the existens of SHA1 already?

**Comment by sukramblak** [comment]
Hi adrianschroeter 

debian 8.0 (apt) treats the the gpg key from [1] in the same way it would treat a none existing repo-key.  Installation looks like there is no check done. 


[1] http://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_16.04/Release.key

**Comment by ad-m** [comment]
```
$ sudo apt-get update 
(…)
W: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.gpg: Signature by key F9EA4996747310AE79474F44977C43A8BA684223 uses weak digest algorithm (SHA1)
(…)
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
$ date
pon, 4 lip 2016, 13:55:47 CEST
```

**Comment by mlschroe** [comment]
Well, isv:ownCloud:desktop has an old DSA key:
```
$ gpg Release.key 
pub  1024D/BA684223 2012-02-08 [expires: 2017-04-19]
uid                            isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
```

So we can't use sha256. Please switch to an RSA key (but notify your customers that the key has changed).

**Comment by mlschroe** [comment]
(ah, I meant isv:ownCloud and not isv:ownCloud:devel. Do not create a key in isv:ownCloud:devel...)

**Comment by mhogomchungu** [comment]
Greetings,
I have been having this problem for months now and i was hoping it will eventually sort itself out but doesnt seem to be happening.

The solution to this problem seems to be a manual switch from a DSA key(default) to an RSA key.

Is it possible to make this switch using the web interface? I could not see any option to do it.

Why isnt the switch not done automatically for everybody?

**Comment by mlschroe** [comment]
The default has been switched to RSA since a couple of years. But there still exist some old DSA keys. We don't force the switch as this means a different keyid will be created, thus it makes the old published pubkey invalid.

**Comment by mhogomchungu** [comment]
How do i force the switch in my account since its not done automatically and i would like to switch?

For example,if i delete my account and recreate it,will it start using RSA key?

My account is at: https://build.opensuse.org/project/show/home:mhogomchungu

**Comment by estan** [comment]
I have exactly the same question as @mhogomchungu , on behalf of the GammaRay project, to which I reported https://github.com/KDAB/GammaRay/issues/319 . What should I tell them that they should do? Is there really no way to trigger generation of a new key (to get RSA) for an existing project?

**Comment by estan** [comment]
@mlschroe Is there anything that existing projects on the public instance (build.opensuse.org) can do to get their keys regenerated (to get an RSA key instead of DSA), short of deleting and recreating the entire project?

**Comment by okin** [comment]
@estan I am currently in process of preparing a key change and found out that the `osc` tool allows change the key.

Creating a new key can be done with: `osc signkey --create home:youruser:project`
You users will have to import the new key.

Then you may want trigger a rebuild of that project to make sure that all alreasy existing packages are signed again with the new key.
The latter step is important if you have users that are running CentOS / RHEL because yum will complain about packages signed with a different key.
To re-import the new key on CentOS you can use rpm: `rpm --import http.../path/to/your/repodata/repomd.xml.key`

**Comment by estan** [comment]
@okin: Ah yes, sorry for not following up on this: I discovered the same thing and relayed that info to the GammaRay developers. They were able to recreate their key, so all is good now :)
